// <autogenerated>
//   This file was generated by T4 code generator SampleScriptTemplates.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


namespace Sitecore.CodeGenerator.Sample.Glass.Models.sitecore.templates.SitecoreCodeGeneratorSample
{
using global::Sitecore.Data;
using global::System;
using global::System.Collections.Generic;
using global::System.Collections.Specialized;
using global::Glass.Mapper.Sc.Configuration.Attributes;
using global::Glass.Mapper.Sc.Configuration;
using global::Glass.Mapper.Sc.Fields;

	/// <summary>
	/// Represents a mapped type for item {319EB0A2-EF28-4DAE-B35C-551BD53317B2} in Sitecore.
	/// Path: /sitecore/templates/Sitecore Code Generator Sample/Animal
	/// </summary>
	[SitecoreType(TemplateId = IAnimalConstants.TemplateIdString, Cachable = true)]
	public partial interface IAnimal: IGlassBase 
	{
		#region Animal

		/// <summary>
		/// A short description of the animal
		/// </summary>
	    [SitecoreField(IAnimalConstants.DescriptionFieldName)]
		string Description { get; set; }

		#endregion

	}

	public static partial class IAnimalConstants
	{
		public const string TemplateIdString = "{319EB0A2-EF28-4DAE-B35C-551BD53317B2}";
		public static readonly ID TemplateId = new ID("{319EB0A2-EF28-4DAE-B35C-551BD53317B2}");
		public const string TemplateName = "Animal";

			
		public static readonly ID DescriptionFieldId = new ID("{EDFD61C6-BBEF-45B6-8FD4-84CA215BAB73}");
		public const string DescriptionFieldName = "Description";
	}
}
